name: Trigger Statefile Workflow

on:
  workflow_dispatch:
    inputs:
      appcode:
        description: 'App Code'
        required: true
      functionalarea:
        description: 'Functional Area'
        required: true
        type: choice
        options: [commercial, dataops, it, global services, m&q, r&d]

jobs:
  trigger_statefile_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Statefile Workflow
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.PAT_STATEFILE }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -d '{"event_type": "run-workflow", "client_payload": {"appcode": "${{ github.event.inputs.appcode }}", "functionalarea": "${{ github.event.inputs.functionalarea }}"}}' \
            https://api.github.com/repos/Rakesh-Gopala/statefile/dispatches
